# Generated by Django 4.1.5 on 2023-02-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinstance',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
