# Generated by Django 4.1.5 on 2023-02-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productinstance_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinstance',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
