# Generated by Django 4.1.5 on 2023-02-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_order_is_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_returned',
            field=models.BooleanField(null=True),
        ),
    ]
