# Generated by Django 4.1.5 on 2023-02-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_last_name_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='money',
            field=models.IntegerField(default=10000),
        ),
    ]
